CREATE TABLE OLINGO.post
(
    ID    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    TITLE VARCHAR(255),
    PRIMARY KEY (ID)
);
CREATE TABLE OLINGO.post_comment
(
    ID      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    REVIEW  VARCHAR(255),
    post_id BIGINT,
    PRIMARY KEY (ID)
);
ALTER TABLE OLINGO.post_comment
    ADD CONSTRAINT FK_post_comment_post_id FOREIGN KEY (post_id) REFERENCES OLINGO.post (ID);

/*
insert into OLINGO.post (title, id)
values ('First post', 1);

insert into OLINGO.post_comment (review, id)
values ('My first review', 2);

insert into OLINGO.post_comment (review, id)
values ('My second review', 3);

insert into OLINGO.post_comment (review, id)
values ('My third review', 4);

update OLINGO.post_comment set post_id = 1 where id = 2;

update OLINGO.post_comment set post_id = 1 where id =  3;

update OLINGO.post_comment set post_id = 1 where id =  4;*/
